name: Crowdin Upload

on:
  push:
    branches:
      - '*-dev'

jobs:

  synchronize-with-crowdin:
    name: Upload strings to Crowdin
    if: github.repository_owner == 'LawnchairLauncher'
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Upload Strings
      uses: crowdin/github-action@v1.6.0
      with:
        upload_translations: false
        upload_sources: true
        download_translations: false
        localization_branch_name: 12.1-dev-localization
        create_pull_request: false
        base_url: 'https://lawnchair.crowdin.com'
      env:
        GITHUB_TOKEN: ${{ secrets.LAWNCHAIR_BOT_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
