name: Crowdin Synchronization

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:

  synchronize-with-crowdin:
    name: Synchronize with Crowdin
    if: github.repository_owner == 'LawnchairLauncher'
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Sync Translations
      uses: crowdin/github-action@1.5.2
      with:
        upload_translations: false
        upload_sources: true
        download_translations: true
        localization_branch_name: 12.1-dev-localization
        create_pull_request: true
        base_url: 'https://lawnchair.crowdin.com'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
